# Generated by Django 4.2.5 on 2023-09-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0003_alter_inventory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
