# Generated by Django 4.2.5 on 2023-10-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0005_alter_inventory_iin_alter_inventory_name_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(default='397221', editable=False, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
