# Generated by Django 4.2.5 on 2023-10-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0006_alter_inventory_iin_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(default='IIN119103', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
