# Generated by Django 4.2.5 on 2023-10-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0007_alter_inventory_iin_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
