# Generated by Django 4.2.5 on 2023-10-01 07:57

from django.db import migrations, models
import imsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0010_alter_inventory_iin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='iin',
            field=models.CharField(default=imsapp.models.key_generator, editable=False, max_length=6, unique=True),
        ),
    ]
