# Generated by Django 4.2.5 on 2023-10-03 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0014_alter_orders_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imsapp.inventory'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='t_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
