# Generated by Django 4.2.5 on 2023-10-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0016_remove_orders_t_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsapp.inventory'),
        ),
    ]
