# Generated by Django 4.2.5 on 2023-10-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0017_alter_orders_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
