# Generated by Django 4.2.5 on 2023-10-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0018_alter_orders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.AddField(
            model_name='orders',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=True, max_digits=10),
            preserve_default=False,
        ),
    ]
