# Generated by Django 4.2.5 on 2023-10-05 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0019_remove_orders_price_orders_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('orid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsapp.orders')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
