# Generated by Django 4.2.5 on 2023-10-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0021_alter_transaction_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
