# Generated by Django 4.2.5 on 2023-10-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imsapp', '0022_alter_transaction_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
